# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool: Default

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: Use .NET 6 Core sdk
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
    includePreviewVersions: true
- task: DotNetCoreCLI@2
  displayName: Running tests
  condition: succeededOrFailed()
  inputs:
    command: test
    projects: '**/*.csproj '
    arguments: /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/Coverage/
- task: PublishCodeCoverageResults@1
  displayName: Publish code coverage
  condition: always()
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: $(Build.SourcesDirectory)\coveragereport\cobertura.xml
    reportDirectory: $(Build.SourcesDirectory)\coveragereport\
    additionalCodeCoverageFiles: $(Build.SourcesDirectory)\coveragereport\*.html    
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build $(buildConfiguration)'